### ISSUE TITLE
double click buffer will open other file named "No name"

### ISSUE THREAD

**Issue by CaoPeng** [ap/vim-buftabline#15]
1、open 2(or more) files
2、:bnext / :bprev to switch buffer --> ok
3、 try double click/click the buffer to switch buffer  -->KO
        --> will open another file named "No name"

**Comment by ap** [comment]
Thanks for prodding me into giving this another shot. I was all set to explain how this was not a bug I could fix, because it’s just how the tabline in Vim works, and plugins cannot control that. And that is still true. But I *could* use some of Vim’s builtin behaviour against itself, which had not occurred to me until now. So your bug ticket made the plugin better. Thank you!

**Comment by ap** [comment]
Oh – it will however still not allow you to switch tabs by clicking on them. [I have tried to make that work](/ap/vim-buftabline/commit/krazy) and failed. I have explained more in #6.

It looks like NeoVim may allow this at some point (according to neovim@neovim#3871) but stock Vim does not.

**Comment by regedarek** [comment]
any updates after neovim 0.2.0?

**Comment by ap** [comment]
@regedarek: I’ve added #32 to track this, so you can watch that if you want to be updated.
