### ISSUE TITLE
How to move the modified indicator to the end of the file name?

### ISSUE THREAD

**Issue by HiCodin** [ap/vim-buftabline#27]
Can you advise me on how I can move the indicator to the end of the file name ?
I've tried editing the plugin code itself but due to my limited viml skills, I can't get it to work. 
Thanks.

**Comment by ap** [comment]
It’s not simple because there are several options and scenarios they all affect each other – so there isn’t one single orthogonal place where this can be changed. Multiple bits of the code need tweaks and all the combinations have to be tested. I’m afraid I can’t be bothered to put in the time to do that for you.

That said, while I am OK with the fact that it’s not simple to change the design drastically, I’m not happy that I have to turn you (and some other users) away. I have been meaning to add some mechanism for redefining the design completely, so that users like you would have an answer. But it’s not there yet, sorry.

**Comment by HiCodin** [comment]
Ah, I see. Thanks for taking in my suggestion.

It really is a tiring process when you have to redo almost everything. For my request, I make do with disabling the indicator in the mean time. Hope you'll get the time to improve this great little plugin. :)
