### ISSUE TITLE
When use quickfix, it will use tabs instead of buffers

### ISSUE THREAD

**Issue by iwifigame** [ap/vim-buftabline#42]
you can use ag or ack plugin to search some text, it will open quickfix. then you will see the picture below
![qq 20171121212732](https://user-images.githubusercontent.com/22087773/33075047-34d05576-cf03-11e7-8dd4-cbe4bcf7b512.png)

**Comment by ap** [comment]
Your screenshot shows more than a single tab page. Note that your first tab shows “NERD_tree_1” – a buffer which isn’t visible on the screenshot. So evidently you legitimately have two different tab pages.

There is nothing in buftabline which can create tab pages, so I don’t believe that it can be the cause. What you see on the screenshot is the fact that buftabline disables itself temporarily when there are multiple Vim tabs. (That’s so you can use your tabs normally, as long as you have them open. If you close them all, you will find that buftabline enables itself again.) (Someday I want to add tab page support to buftabline itself. Then it’ll show a tiny list of tab page numbers on one end of the tabline instead of turning itself off.)

I don’t know what exactly what part of your configuration would be creating new tab pages.

Does that cover your question?

**Comment by iwifigame** [comment]
When I not use buftabline, use ag it didn't open tabs. So I think it may be the buftabline problem.

**Comment by iwifigame** [comment]
And when I use minibuffer or airline plugin to show buffers, when use ag them also not open tabs.

**Comment by iwifigame** [comment]
Sorry, I  found it's because CtrlP has set switchbuf="useropen,usertab,tabnew". Just set swichbuf to default "" to fix this problem.

**Comment by ap** [comment]
No worries. 😊
