### ISSUE TITLE
Is this project dead

### ISSUE THREAD

**Issue by astier** [ap/vim-buftabline#70]
Hi. I really like your plugin. Thanks a lot for your work. I am wondering if you have plans to work on it further or if this project is dead?

**Comment by ap** [comment]
It’s certainly alive. That doesn’t mean I have big plans to add a million new features or make massive changes. I do have some plans, and they have been a long time coming, but that’s because I want to go about them carefully. The plugin is simply at a place where it does the most important thing it’s supposed to, in the way it’s supposed to, and doesn’t *need* a lot of changes. But there are some missing features, and I will definitely be fixing any bugs if they come up, and adapting it to continue working in the face of Neo-/Vim changes.
