### ISSUE TITLE
opening a vim terminal buffer breaks tab switching

### ISSUE THREAD

**Issue by phelps-sg** [ap/vim-buftabline#81]
Steps to reproduce:

1. Open several text buffers.
2. Open a [terminal buffer](https://vimhelp.org/terminal.txt.html) in a new window.
3.  Switch between buffers using ^N or ^P until you get to the terminal buffer

When the terminal buffer is encountered no further cycling through buffers is possible until the terminal is switched into [terminal normal mode](https://vimhelp.org/terminal.txt.html#Terminal-mode).  This has to be done every time the terminal buffer is encountered when switching.  This gets tedious very quickly if you regularly keep a terminal buffer open.

Maybe terminal buffers should be hidden from the tabs?

**Comment by phelps-sg** [comment]
This is not an issue with vim-buftabline- I found the solution here:
https://vi.stackexchange.com/questions/16708/switching-buffers-in-vi-while-skipping-any-terminal-in-vi-8-1

**Comment by ap** [comment]
Just now getting to take a look at this (since you answered yourself so quickly), and indeed, this has to do with Buftabline only insofar as you would get these issues if you set up the mappings suggested by the quick intro in the Buftabline README. But Buftabline itself intentionally includes no buffer management, by design, and so addressing this issue isn’t in its purview.
